import { verifyCloudProof, IVerifyResponse } from "@worldcoin/idkit-core/backend";
import { ISuccessResult } from "@worldcoin/idkit-core";

export interface WorldVerificationRequest {
  proof: ISuccessResult;
  signal?: string;
}

/**
 * World Selfie Check Verification Service
 * Validates the zero-knowledge proof generated by World App Selfie Check against World's Cloud Verification API.
 */
export async function verifyWorldSelfieProof(
  proof: ISuccessResult,
  signal?: string
): Promise<{ success: boolean; error?: string; code?: string }> {
  const appId = (process.env.NEXT_PUBLIC_WORLD_APP_ID || "app_9af54079c0ae44169e8a21df561ec2d3") as `app_${string}`;
  const rpId = process.env.NEXT_PUBLIC_WORLD_RP_ID || "rp_c1e0eb1e9616e85c";
  const action = process.env.NEXT_PUBLIC_WORLD_ACTION || "float-human-verify";

  // 1. Primary: World ID 4.0 Verification via Relying Party API (/api/v4/verify/{rp_id})
  if (rpId) {
    try {
      console.log(`[World-Verify v4] Attempting RP verification at https://developer.world.org/api/v4/verify/${rpId}`);

      const v4Payload: Record<string, any> = {
        protocol_version: "3.0",
        action,
        nonce: String(Date.now()),
        responses: [
          {
            identifier: proof.verification_level || "device",
            nullifier: proof.nullifier_hash,
            merkle_root: proof.merkle_root,
            proof: proof.proof,
            verification_level: proof.verification_level || "device",
          },
        ],
      };

      if (signal) {
        v4Payload.signal_hash = signal;
      }

      const v4Response = await fetch(`https://developer.world.org/api/v4/verify/${rpId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(v4Payload),
      });

      const v4Data = await v4Response.json();
      console.log("[World-Verify v4] API Response:", v4Response.status, JSON.stringify(v4Data));

      if (v4Response.ok && (v4Data.success === true || v4Data.results?.[0]?.success === true)) {
        return { success: true };
      }

      // Check if v4 provided detailed failure reasons
      if (v4Data.results && Array.isArray(v4Data.results) && v4Data.results[0]) {
        const item = v4Data.results[0];
        if (item.success === true) {
          return { success: true };
        }
        return {
          success: false,
          code: item.code || v4Data.code,
          error: item.detail || v4Data.detail || "Proof verification failed",
        };
      }

      if (v4Data.detail || v4Data.code) {
        return {
          success: false,
          code: v4Data.code,
          error: v4Data.detail || "Proof verification failed",
        };
      }
    } catch (v4Err: any) {
      console.warn("[World-Verify v4] Error during v4 call, falling back to legacy v2:", v4Err.message);
    }
  }

  // 2. Fallback: World ID v2 verifyCloudProof
  try {
    const result: IVerifyResponse = await verifyCloudProof(proof, appId, action, signal);

    if (result.success) {
      return { success: true };
    }

    return {
      success: false,
      code: result.code,
      error: result.detail || result.code || "World ID Selfie Check verification rejected",
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || "Failed to communicate with World Developer API",
    };
  }
}
